### ISSUE TITLE
Billetera copay

### ISSUE THREAD

**Issue by Copaymartin** [particl/copay#38]
He wrote to ask:
How can i get my bitcoin back? . I lost my cell phone and I don't remember my phrase. I had downloaded copay and kept my bitcoins there.
![Screenshot_20200513-214907](https://user-images.githubusercontent.com/65320541/81881382-6ad88900-9566-11ea-93cc-11e43dd2b8ac.jpg)

**Comment by Copaymartin** [comment]
![Screenshot_20200514-081212](https://user-images.githubusercontent.com/65320541/81929557-99ce1980-95bd-11ea-80cc-8b1371d4a638.jpg)
Hola, pude encontrar mi frase, pero cua do la pongo en mi nuevo dispositivo me aparece esta imagen

**Comment by rynomster** [comment]
Hi @Copaymartin. Your wallet seems like a bitpay wallet and not a Particl Copay wallet

Try download Bitpay from the app store and import your code there

**Comment by Copaymartin** [comment]
> Hi @Copaymartin. Your wallet seems like a bitpay wallet and not a Particl Copay wallet
> 
> Try download Bitpay from the app store and import your code there

Hola @rynomster descargue Bytpay y cuando cargo la frase no me reconoce la  billetera, no me la rechaza, pero no me trae ningún bitcoin de lo que habia comprado en febrero de 2018.

**Comment by rynomster** [comment]
can you send me an email, so that I can try assist?
ryno@particl.io
