### ISSUE TITLE
Staked transactions should say staked instead of moved

### ISSUE THREAD

**Issue by rynomster** [particl/copay#5]
In the transaction history view, all staked transactions show up as moved, and foundation payout transactions show up as sent instead of staked

**Comment by imybb** [comment]
![screenshot_20171027-162935_01](https://user-images.githubusercontent.com/30150617/32119172-525fcf42-bb4c-11e7-9f34-ce80acacf6ac.jpg)

**Comment by rynomster** [comment]
See PBD-139

**Comment by rynomster** [comment]
Sorry testing Jira integration, but I'm not sure if its working :(

**Comment by rynomster** [comment]
Not sure why PBD-139 #comment comments aren't working

**Comment by rynomster** [comment]
[[PBD-139]](https://particl.atlassian.net/browse/PBD-139) This should possibly work?

**Comment by spazzymoto** [comment]
Closing this as done after the last release
